pub mod accessories;
pub mod alignment;
pub mod analysis;
pub mod blast;
pub mod col_summary;
pub mod color_editor;
pub mod command_palette;
pub mod composition;
pub mod conservation;
pub mod dot_plot;
pub mod help;
pub mod hydrophobicity;
pub mod identity_matrix;
pub mod mutual_info;
pub mod oligo_tm;
pub mod orfs;
pub mod pairwise;
pub mod plasmid;
pub mod prefs_dialog;
pub mod seq_editor;
pub mod shaded_export_dialog;
pub mod sixframe;
pub mod taxonomy;
pub mod text_export_dialog;
pub mod trace;
pub mod tree;
pub mod welcome;

pub use accessories::accessories_view;
pub use alignment::alignment_view;
pub use analysis::analysis_panel;
pub use blast::blast_view;
pub use col_summary::col_summary_view;
pub use color_editor::color_editor_view;
pub use command_palette::{
    command_palette, fire as palette_fire, match_count as palette_count,
    resolve_selected as palette_resolve,
};
pub use composition::composition_view;
pub use conservation::conservation_view;
pub use dot_plot::dot_plot_view;
pub use help::help_view;
pub use hydrophobicity::hydrophobicity_view;
pub use identity_matrix::identity_matrix_view;
pub use mutual_info::{mutual_info_view, MiTab};
pub use oligo_tm::oligo_tm_view;
pub use orfs::orfs_view;
pub use pairwise::pairwise_view;
pub use plasmid::{plasmid_to_svg, plasmid_view};
pub use prefs_dialog::prefs_dialog;
pub use seq_editor::seq_editor_view;
pub use shaded_export_dialog::shaded_export_dialog;
pub use sixframe::sixframe_view;
pub use taxonomy::taxonomy_view;
pub use text_export_dialog::text_export_dialog;
pub use trace::trace_view;
pub use tree::tree_view;
pub use welcome::welcome_view;
